config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  delete 'uninvite' => 'invitations#destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :events
  resources :invitations, only: [:create]
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :host, class_name: "User"
  has_many :invitations, dependent: :destroy
  has_many :guests, through: :invitations, source: :guest

  validates :title, presence: true, length: {maximum:255},
            uniqueness: true
  validates :date, presence:true
  validates :description, presence: true

  scope :upcoming, -> {where('date >= ?', Time.now)}
  scope :past,         -> {where('date < ?', Time.now)}
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :guest, class_name: "User"
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :invitations, foreign_key: :guest_id, dependent: :destroy
  has_many :events, foreign_key: :host_id
  has_many :attendances, through: :invitations, source: :event

  before_save :downcase_email

  validates :name, presence: true, length: {maximum:50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:255},
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, presence: true, length: {minimum:6},
            allow_nil: true

  def downcase_email
    self.email = email.downcase
  end

  def User.create_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(string)
    Digest::SHA1.hexdigest(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  def signed_in_user
    unless signed_in?
      redirect_to new_session_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create]

  def index
    @upcoming_events = Event.upcoming
    @past_events = Event.past
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "Event created."
      redirect_to @event
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @user = @event.host
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update_attributes(event_params)
    if @event.save
      flash[:success] = "Event has been updated."
      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])
    @user = event.host
    event.destroy
    flash[:success] = "Event has been deleted."
    redirect_to @user
  end

  private

  def event_params
    params.require(:event).permit(:title, :date, :location, :description)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :correct_user

  def create
    @event = Event.find(params[:event_id])
    guest = User.find_by(email: params[:invitation][:guest_email])
    if guest && @event
      @event.invitations.create(guest_id: guest.id)
      flash[:success] = "You have added #{guest.name} to this event."
      redirect_to @event
    else
      flash[:danger] = "Please try again."
      redirect_to @event
    end
  end

  def destroy
    @event = Event.find(params[:event_id])
    invitation = Invitation.find_by(event_id: params[:event_id], guest_id: params[:guest_id])
    invitation.destroy
    flash[:success] = "You have successfully declined this event."
    redirect_to @event
  end

  private

  def correct_user
    user = User.find(params[:id])
    unless user == current_user
      flash[:danger] = "You are not authorized!"
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      sign_in @user
      flash[:success] = "You are signed in."
      redirect_to @user
    else
      flash[:danger] = "Invalid email or password."
      redirect_to new_session_path
    end
  end

  def destroy
    user = User.find(params[:id])
    logout(user)
    flash[:success] = "You logged out."
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:show]

  def index
    @upcoming_events = Event.upcoming.limit(3)
    @past_events = Event.past.limit(3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "You have successfully created account."
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.events.upcoming
    @invitations = @user.attendances
    @past_events = @user.events.past
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    if @user.save
      flash[:success] = "Your account has been updated."
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    logout(user)
    @current_user = nil
    user.destroy
     flash[:success] = "Your account has been deleted."
     redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def upcoming_event?(event)
    Event.upcoming.include? event
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.create_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_digest, User.digest(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def logout(user)
   user.remember_digest = nil
   cookies.delete(:remember_token)
  end

  def current_user
    remember_token = cookies[:remember_token]
    if remember_token
    @current_user ||= User.find_by(remember_digest: User.digest(remember_token))
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def logged_in_user
    unless signed_in?
      redirect_to new_session_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def creator?(user)
    if current_user
      current_user.id == user.id
    end
  end
end

app/views/events/_event.html.erb
<% if upcoming_event?(event) %>
<h3><%= link_to event.title, event_path(event.id) %></h3>
<% else %>
<h3><%= event.title %></h3>
<% end %>
<p>Date:<%= event.date.to_formatted_s(:rfc822) %></p>
<p>Location:<%= event.location %></p>
<% if creator?(event.host) %>
<p>Hosted by : You</p>
<% else %>
<p>Hosted by : <%= event.host.name %></p>
<% end %>

app/views/events/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @event, html: {class: "form-horizontal"} do |f| %>
    <div class="form-group">
      <%= f.label :title, class: "control-label col-sm-4" %>
      <%= f.text_field :title, class: "col-sm-8"  %>
    </div>

    <div class="form-group">
      <%= f.label :event_date, class: "control-label col-sm-4" %>
      <%= f.date_field :date, class: "col-sm-8"  %>
    </div>

    <div class="form-group">
      <%= f.label :location, class: "control-label col-sm-4" %>
      <%= f.text_field :location, class: "col-sm-8"  %>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "control-label col-sm-4" %>
      <%= f.text_field :description, class: "col-sm-8"  %>
    </div>

    <div class="center">
      <%= f.submit "Submit", class: 'btn btn-primary' %>
    </div>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<h1 class="center">Edit event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<div class="row center">
  <div class="col-md-6">
    <h2>Upcoming Events</h2>
    <%= render @upcoming_events %>
  </div>
  <div class="col-md-6">
    <h2>Past Events</h2>
    <%= render @past_events %>
  </div>
</div>

app/views/events/new.html.erb
<h1 class="center">Create event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="pull-right">
  <%= link_to "Edit", edit_event_path(@event), class: "btn btn-primary" %>
  <%= link_to "Cancel Event", event_path(@event), method: 'delete',
  class: "btn btn-primary",
    data: {confirm: "Are you sure you want to delete this event?"} %>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h1><%= @event.title %></h1>
      <p>Taking place on: <%= @event.date.strftime("%d/%m/%Y") %></p>
      <p>At: <%= @event.location %></p>
      <p>Description:<%= @event.description %></p>
      <% if creator?(@user) %>
      <%= form_for(:invitation, url: invitations_path) do |f| %>
      <p>
        <%= hidden_field_tag :event_id, @event.id %>
        <%= hidden_field_tag :id, @event.host.id %>
        <%= f.label "Enter guest's email:" %>
        <%= f.text_field :guest_email %>
        <%= f.submit "Invite", class: "btn btn-primary" %>
      </p>
      <% end %>
      <% end %>
    </div>
    <div class="col-md-6">
      <h1>Guests:</h1>
      <% @event.guests.each do |guest| %>
      <p>
        <%= guest.name %>
        <%= form_for(:uninvite, url: uninvite_path, method: 'delete') do |f| %>
        <%= hidden_field_tag :event_id, @event.id %>
        <%= hidden_field_tag :guest_id, guest.id %>
        <%= hidden_field_tag :id, current_user.id %>
        <%= f.submit "Uninvite", class: "btn btn-primary" %>
        <% end %>
      </p>
      <% end %>
    </div>
  </div>

app/views/layouts/_navbar.html.erb
<div class="header clearfix">
  <nav>
    <ul class="nav nav-pills pull-right">
      <li role="presentation"><%= link_to "Events", events_path %></li>
      <% if signed_in? %>
        <li role="presentation"><%= link_to "My Events", user_path(current_user) %></li>
        <li role="presentation"><%= link_to "Create Event", new_event_path %></li>
        <li role="presentation"><%= link_to "Log out", session_path(current_user), method: 'delete' %></li>
      <% else %>
        <li role="presentation"><%= link_to "Log in", new_session_path %></li>
      <% end %>
    </ul>
  </nav>
  <h3 class="text-muted"><%= link_to "Private Events", root_url %></h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <%= render 'layouts/navbar' %>
  <%= yield %>

</div>



</body>
</html>

app/views/users/_register_form.html.erb
<%= form_for @user, html: {class: "form-horizontal"} do |f| %>
    <div class="form-group">
      <%= f.label :name, class: "control-label col-sm-4" %>
      <%= f.text_field :name, class: "col-sm-8" %>
    </div>
    <div class="form-group">
      <%= f.label :email, class: "control-label col-sm-4" %>
      <%= f.text_field :email, class: "col-sm-8" %>
    </div>
    <div class="form-group">
      <%= f.label :password, class: "control-label col-sm-4" %>
      <%= f.password_field :password, class: "col-sm-8" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, class: "control-label col-sm-4" %>
      <%= f.password_field :password_confirmation, class: "col-sm-8" %>
    </div>
    <div class="center">
      <%= f.submit "Register", class: 'btn btn-primary' %>
    </div>

    <% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'register_form' %>

app/views/users/index.html.erb
<div class="row center">
<div class="col-md-6">
    <h2>Recent Events</h2>
    <%= render @upcoming_events %>
  </div>
  <div class="col-md-6">
    <h2>Recently Passed Events</h2>
    <%= render @past_events %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="center">Register</h1>

    <%= render 'register_form' %>

  </div>
</div>

app/views/users/show.html.erb
<div class="pull-right">
<%= link_to 'Delete account', user_path(current_user), method: 'delete', class: 'btn btn-default' %>
<%= link_to 'Edit account', edit_user_path(current_user), class: 'btn btn-default' %>
</div>

<% if creator?(@user) %>
<h1 style="text-align: center;">Hello, <%= @user.name %>!</h1>
<% else %>
<h1 style="text-align: center;"><%= @user.name %>'s Events</h1>
<% end %>

<div class="row center">
  <div class="col-md-4">
    <h2>Your Upcoming Events</h2>
    <% if @upcoming_events.count == 0 %>
    <p>You don't have any upcoming events. <%= link_to "Create event", new_event_path %>?</p>
    <% else %>
    <p>You have <%= pluralize(@upcoming_events.count, 'event')%>.</p>
    <%= render @upcoming_events %>
    <% end %>
  </div>
  <div class="col-md-4">
    <h2>Invitations</h2>
    <% @invitations.each do |event| %>
    <h3><%= event.title %></h3>
    <p>Date:<%= event.date.to_formatted_s(:rfc822) %></p>
    <p>Location:<%= event.location %></p>
    <p>Description:<%= event.location %></p>
    <p>Hosted by : <%= event.host.name %></p>
      <%= form_for(:decline, url: uninvite_path, method: 'delete') do |f| %>
      <%= hidden_field_tag :event_id, event.id %>
      <%= hidden_field_tag :guest_id, current_user.id %>
      <%= hidden_field_tag :id, params[:id] %>
      <%= f.submit "Decline", class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-4">
    <h2>Past events</h2>
    <% if @past_events.count == 0 %>
    <p>You don't have any past events.</p>
    <% else %>
    <p>You had <%= pluralize(@past_events.count, 'event')%>.</p>
    <%= render @past_events %>
    <% end %>
  </div>
</div>